---
- name: cleanup docker on  KafkaClusters
  hosts: MyChameleonVMs
  remote_user:  cc
  become: true
  gather_facts: no

  tasks:
  - name: cleanup services
    shell: |
        docker  service rm $(docker service ls -q)
  - name: cleanup container
    shell: |
        docker container rm $(docker container ls -aq)
  - name: cleanup images
    shell: |
        docker image rm $(docker image ls -aq)
 ...
