---
- name:  create default:default service account
  hosts: Master
  remote_user:  ubuntu
  become: true
  tasks:
    - name: create default:default service account
      shell: kubectl create clusterrolebinding default   --clusterrole=edit --serviceaccount=default:default --namespace=default

...
