---
- name:  setup k8s worker
  hosts: Master
  remote_user:  cc
  become: true
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name:  setup addon
  hosts: AddonVMs
  remote_user:  cc
  become: true
  gather_facts: false
  tasks:
    - name: join cluster
      shell: "{{ hostvars['Teame3-KafkaCluster1'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
...
