apiVersion: v1
kind: Service
metadata:
  name: kafka-2-ip-service
spec:
#  type: ClusterIP
  type: NodePort 
  selector:
    component: kafka-2
  ports:
  - name: kafka-ext
    port: 9093
    targetPort: 9093
    nodePort: 30002



  
