apiVersion: v1
kind: Service
metadata:
  name: kafka-4-ip-service
spec:
  type: NodePort 
  selector:
    component: kafka-4
  ports:
  - name: kafka-ext
    port: 9093
    targetPort: 9093
    nodePort: 30004



  
