apiVersion: v1
kind: Service
metadata:
  name: kafka-3-inner-ip-service
spec:
  type: ClusterIP
  selector:
    component: kafka-3
  ports:
  - name: kafka-int
    port: 9092
    targetPort: 9092



  
