apiVersion: v1
kind: Service
metadata:
  name: kafka-5-ip-service
spec:
  type: NodePort 
  selector:
    component: kafka-5
  ports:
  - name: kafka-ext
    port: 9093
    targetPort: 9093
    nodePort: 30005



  
