apiVersion: v1
kind: Service
metadata:
  name: kafka-1-inner-ip-service
spec:
  type: ClusterIP
#  type: NodePort 
  selector:
    component: kafka-1
  ports:
  - name: kafka-int
    port: 9092  #from pod  
    targetPort: 9092  #to cluster net #for brokes to see each other
#  - name: kafka-ext
#    port: 9093
#    targetPort: 9093
#    nodePort: 30001



  
