apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: zookeeper
  template:
    metadata:
      labels:
        component: zookeeper
    spec:
      volumes:
      - name: zoo-data
        emptyDir: {}
      containers:
      - name: zookeeper
        image: kafka-zk:1.0       
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
          - containerPort: 2181
        volumeMounts:
          - name: zoo-data
            mountPath: "/tmp/zookeeper"
        command: ["/kafka/bin/zookeeper-server-start.sh"]
        args: ["/kafka/config/zookeeper.properties"]
        tty: true
#        livenessProbe:
#          exec:
#            command:
#              - /opt/check.sh
#          initialDelaySeconds: 30
#          periodSeconds: 30
#        readinessProbe:
#          exec:
#            command:
#              - /opt/check.sh
#          initialDelaySeconds: 30
#          periodSeconds: 5
#      imagePullSecrets:
#        - name: regcred
      
