# Author: Aniruddha Gokhale
# Vanderbilt University
# Created Nov 2017
#
# For Cloud Computing class
#
# Docker build file for our MapReduce master
#

# First, use the latest ubuntu image
FROM python/spark-py:1.0

USER 0

RUN pip3 install pyzmq

#
# copy the files needed to run the spark application
#COPY work /root/

USER ${185}
#
# Run a command shell
# Note that we do not run the wordcount directly as the service
# in our swarm otherwise when the wordcount completes, the container
# will die. So we manually do a "docker exec" from a separate shell
# while allowing the service to start this container with just a shell
CMD /bin/bash
